CREATE TABLE IF NOT EXISTS users (
    id int generated by default as identity primary key,
    first_name VARCHAR(50) default 'noname user',
    last_name VARCHAR(50) default 'noname user',
    email VARCHAR(100) NOT NULL,
    state VARCHAR(50) NOT NULL CHECK (state IN ('ACTIVE', 'BLOCKED', 'DELETED')),
    registration_date TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS items (
    id int generated by default as identity primary key,
    user_id int NOT NULL,
    url VARCHAR(256) NOT NULL,
    title VARCHAR(512) NOT NULL,
    mime_type VARCHAR(256) NOT NULL,
    has_image boolean,
    has_video boolean,
    resolved_url VARCHAR(512) NOT NULL,
    date_resolved TIMESTAMP,
    CONSTRAINT fk_users
    foreign key (user_id)
    references users (id)
    );

CREATE TABLE IF NOT EXISTS tags (
    id int generated by default as identity primary key,
    name VARCHAR(256) NOT NULL,
    item_id int NOT NULL,
    CONSTRAINT fk_items
    foreign key (item_id)
    references items (id)
    );