CREATE TABLE IF NOT EXISTS users (
    id int generated by default as identity primary key,
    first_name VARCHAR(50) default 'noname user',
    last_name VARCHAR(50) default 'noname user',
    email VARCHAR(100) NOT NULL,
    state VARCHAR(50) NOT NULL CHECK (state IN ('ACTIVE', 'BLOCKED', 'DELETED'))
    registration_date date
    );

CREATE TABLE IF NOT EXISTS items (
    id int generated by default as identity primary key,
    url VARCHAR(256) NOT NULL,
    user_id int NOT NULL,
    CONSTRAINT fk_users
    foreign key (user_id)
    references users (id)
    );

CREATE TABLE IF NOT EXISTS tags (
    id int generated by default as identity primary key,
    name VARCHAR(256) NOT NULL,
    item_id int NOT NULL,
    CONSTRAINT fk_items
    foreign key (item_id)
    references items (id)
    );